version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    links:
      - php
      - redis
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data